# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  
#-------------------------------
# General Site Settings
title: Stephanie Kriewall
description: "Hi, I'm Stephanie, and I'm excited to bring my strong programming foundation and statistical expertise to a Data Scientist role. My portfolio focuses on interesting projects I have undertaken, emphasizing business impact. Please visit my LinkedIn or download my Resume by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Thornton, CO"
resume_url: /docs/Stephanie_Kriewall_Resume_Data_Scientist.pdf
avatar_image: /img/profile.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/skriewall" # Add your linkedln handle
github: "https://github.com/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/











